### ISSUE TITLE
Editar os comandos do docker

### ISSUE THREAD

**Issue by werdelesmarcio** [SCORP1ON-TEAM/osint#4]
Julio, os comandos do docker no readme do git está apontando para scorpion ainda.

**Comment by Jul10l1r4** [comment]
Corrigio :)

**Comment by D4201** [comment]
✔─[No project]─[12:11]
├─[u0_a187@localhost]─{~}
└─➤ pkg update
The program pkg is not installed. Install it by executing:
 pkg install termux-tools
✘─[No project]─[12:12] # 127
├─[u0_a187@localhost]─{~}
└─➤

Sorry, I only asked about, why does my device look like it can't be used? I just learned about computer systems, and after I searched the github website I met your script. can you explain? why can't i use the script? 
sorry I just tried just trying all the scripts on this web. However, it's only yours that I can't use, and change the appearance of my device. is there something wrong with me? 
thanks.
